### ISSUE TITLE
align2fasta error - "Couldn't extract sequence align date."

### ISSUE THREAD

**Issue by npavlovikj** [hammerlab/prohlatype#147] opened 2018-05-16 23:50 UTC
Hi,

I tried using "prohlatype" 0.9.0 with the pre-compiled binaries and the Docker image. Although "align2fasta --help" works fine, when I run the test example using IMGT/HLA, I get the following error in both cases:
**_opam@6362de72010a:~$ align2fasta imgthla/alignments/ -o imputed_hla_class_I
align2fasta: internal error, uncaught exception:
             Prohlatype__MSA.Parser.Error("Couldn't extract sequence align date.")
             Raised at file "pervasives.ml", line 436, characters 14-31
             Called from file "src/lib/mSA.ml", line 359, characters 26-41
             Called from file "src/lib/mSA.ml", line 367, characters 6-21_**

Am I missing something in the setup?

I would appreciate any suggestions and help regarding this matter.

Thank you,
Natasha

**Comment by rleonid** [comment] 2018-05-16 23:56
Maybe there's something wrong with the docker image.

Does `imgthla/alignments` contain [these](https://github.com/ANHIG/IMGTHLA/tree/Latest/alignments) files?

**Comment by npavlovikj** [comment] 2018-05-16 23:59
Yes, the IMGT/HLA clone contains all the files from the repo, and I can open and modify them. I got the error above with both the Docker image and the Linux pre-compiled binaries as well.

**Comment by rleonid** [comment] 2018-05-17 00:29
I assume "HPA" was a typo?

3.1.0 is too far back. The last version that I tested prohlatype against was 3240. You can just checkout that branch.

**Comment by npavlovikj** [comment] 2018-05-17 00:40
Hah, yes, it was :) @rleonid , I am so sorry, but I keep getting the same error with 3240 too... Do you maybe have another test file I can try with "align2fasta"?

**Comment by rleonid** [comment] 2018-05-17 00:52
I'm sorry. Yes, 3.240 doesn't work (the release notice is written differently). `3310` seems to be the last branch that works. Again, apologies for all of the difficulties.

**Comment by npavlovikj** [comment] 2018-05-17 01:54
Thanks @rleonid  - that branch worked perfectly with both the binaries and the Docker image. And no apologies needed - I am glad we figured this out in a timely manner :)

**Comment by rleonid** [comment] 2018-05-17 02:11
Glad that it works. I hope that you find prohlatype useful.

I'll keep the issue open until I fix it later this week.

**Comment by rleonid** [comment] 2018-05-19 00:26
Fixed in master.

**Closed by rleonid** 2018-05-19 00:26 UTC

**Comment by kloot** [comment] 2019-01-27 10:19
Hi @rleonid,
I'm getting the same error, both with the binaries from zip archives for 0.8 and 0.9, and the docker container built with run-example-docker.sh (also both versions), The files that raise the exceptions are slightly different in both versions.
Is there another imgt format change? Below is the top of `imgthla/alignments/A_gen.txt`. 
Thanks in advance for your help!

    # file: A_gen.txt
    # date: 2019-01-23
    # version: IPD-IMGT/HLA 3.35.0
    # origin: http://hla.alleles.org/wmda/A_gen.txt
    # repository: https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/A_gen.txt
    # author: WHO, Steven G. E. Marsh (steven.marsh.ac.uk)
    
    gDNA              -300
                      |
    A*01:01:01:01     CAGGAGCAGA GGGGTCAGGG CGAAGTCCCA GGGCCCCAGG CGTGGCTCTC AGGGTCTCAG GCCCCGAAGG CGGTGTATGG ATTGGGGAGT CCCAGCCTTG

**Comment by rleonid** [comment] 2019-01-27 17:49
Yea, looks like it.

[Here](https://github.com/hammerlab/prohlatype/blob/master/src/lib/mSA.ml#L361) is where I look for the release date. Apologies, but I don't have the resources to keep altering the prohlatype parser to maintain compatibility. Feel free to fork, and/or send a PR... or unfortunately, use an older version of IMGT. Or you could write a script to modify their headers to the old style; probably the easiest if you're not familiar with OCaml.

**Comment by kloot** [comment] 2019-01-28 07:19
Hi @rleonid, thanks for your quick reply. Would it be possible for you to attach an IMGT file header that still works with v 0.9.0? I'd like to try writing a modifier script that restores the old style.
Many thanks in advance!

**Comment by rleonid** [comment] 2019-01-30 03:10
@kloot Can you post a stack trace, I'm unable to reproduce against master and the latest IMGT.

**Comment by rleonid** [comment] 2019-01-31 01:11
@kloot Can you check against master?

**Comment by kloot** [comment] 2019-01-31 06:53
@rleonid, I assume you wanted me to build from source?
Following the build instructions on Readme.md, it fails with what looks like problems related to opam. 
I'm not familiar with opam at all but tried around a little with no overall luck. 
Any chance you could update the docker container ?

opam switch 4.05.0
# Run eval $(opam env) to update the current shell environment
eval $(opam env)
make setup
opam install --deps-only ./prohlatype.opam
[WARNING] Failed checks on prohlatype package definition from source at git+file:///home/kbl/APPS/prohlatype#master:
    error 57: Synopsis and description must not be both empty
The following dependencies couldn't be met:
  - prohlatype → ocaml >= 4.06
      base of this switch (use `--unlock-base' to force)

No solution found, exiting
Makefile:9: recipe for target 'setup' failed
make: *** [setup] Error 20
opam switch 4.06.0
# Run eval $(opam env) to update the current shell environment
eval $(opam env)
make setup
opam install --deps-only ./prohlatype.opam
[WARNING] Failed checks on prohlatype package definition from source at git+file:///home/kbl/APPS/prohlatype#master:
    error 57: Synopsis and description must not be both empty
The following dependencies couldn't be met:
  - prohlatype → biocaml >= 0.8.0 → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
  - prohlatype → biocaml >= 0.8.0 → dune
  - prohlatype → jbuilder = 1.0+beta20
Your request can't be satisfied:
  - dune is in conflict with jbuilder != transition

No solution found, exiting
Makefile:9: recipe for target 'setup' failed
make: *** [setup] Error 20
